server.port: 8080
dsyy.db1:
  schema: dsyy
  jdbcUrl: jdbc:mysql://localhost:3306/dsyy?useUnicode=true&characterEncoding=utf8&autoReconnect=true&rewriteBatchedStatements=true
  driverClassName: com.mysql.cj.jdbc.Driver
  username: root
  password: 123456